# Write it!

Lint/PluginLogLevel:
  Description: 'Warn global scope `$log` was used in Fluentd plugin. The scope of plugin log level was supported since Fluentd 0.10.43'
  Enabled: pending
  VersionAdded: '<<next>>'
