# Write it!

Lint/FluentdPluginConfigParamDefaultTime:
  Description: 'Warn the default value of :time for config_param is string'
  Enabled: true
  VersionAdded: '0.1.1'

Lint/FluentdPluginLogScope:
  Description: 'Warn global scope `$log` was used in Fluentd plugin. The scope of plugin log level was supported since Fluentd 0.10.43'
  Enabled: true
  AssumeConfigLogLevel: 'info'
  VersionAdded: '0.1.0'

Lint/FluentdPluginIgnoreStandardError:
  Description: 'Warn if StandardError was shelved in #write. It makes hard to resume from recoverable error.'
  Enabled: true
  VersionAdded: '0.2.4'

Performance/FluentdPluginLogStringInterpolation:
  Description: 'Warn if log message contains string interpolation. Use block to delay needless string interpolation'
  Enabled: true
  VersionAdded: '0.1.0'
